/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bcmhwvyhcfprempdnjzn";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjbWh3dnloY2ZwcmVtcGRuanpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4OTU5MzEsImV4cCI6MjA5MDQ3MTkzMX0.TbIwmlrgqFZRQUuW_d_NXG-jT4BRqFFCNCbruq5QRyg";
